[rrc2022]
task = "lift"  # "push" or "lift"
dataset_type = "expert"  # "expert or "mixed"

# Specify a policy for each task/dataset_type combination.
#push_expert_policy = "rrc2022.example.TorchPushPolicy"
#lift_expert_policy = "rrc2022.example.TorchLiftPolicy"
#push_mixed_policy = "rrc2022.example.TorchPushPolicy"
#lift_mixed_policy = "rrc2022.example.TorchLiftPolicy"


push_expert_policy = "rrc2022.example_cython.TorchPushPolicy"
lift_expert_policy = "rrc2022.example_cython.TorchLiftPolicy"
push_mixed_policy = "rrc2022.example_cython.TorchPushPolicy"
lift_mixed_policy = "rrc2022.example_cython.TorchLiftPolicy"